name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    environment: dev
    runs-on: ubuntu-20.04
    container:
      image: lambci/lambda:build-python3.7
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements-dev.txt
          pytest -vs tests/
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          chalice deploy --stage dev