name: test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: lambci/lambda:build-python3.7
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements-dev.txt
          pytest -vs tests/

